name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master # 获取最新提交的代码

    # 将私钥作为GitHub Secrets存储起来
    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Copy Files Over SSH to Remote Server
      run: |
        rsync -avz --exclude=.git --exclude=config.json ./ root@${{ secrets.HOST_IP }}:${{ secrets.REMOTE_DIR }}