name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: github
          MYSQL_DATABASE: github
          MYSQL_USER: github
          MYSQL_PASSWORD: github
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v3
      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Migration
        run: |
          python manage.py makemigrations blackboard
          python manage.py makemigrations wechat
          python manage.py migrate
      - name: Run Tests
        env:
          BB_USERNAME: ${{ secrets.BB_USERNAME }}
          BB_PASSWORD: ${{ secrets.BB_PASSWORD }}
        run: |
          python manage.py test apps/
  
  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master # 获取最新提交的代码

    # 将私钥作为GitHub Secrets存储起来
    - name: Setup SSH Keys
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ${{ secrets.HOST_IP }} >> ~/.ssh/known_hosts

    - name: Install rsync
      run: sudo apt-get update && sudo apt-get install -y rsync

    - name: Copy Files Over SSH to Remote Server
      run: |
        rsync -avz --exclude=.git --exclude=config.json ./ root@${{ secrets.HOST_IP }}:${{ secrets.REMOTE_DIR }}